export const INVESTMENT_FETCH = 'INVESTMENT_FETCH';
export const INVESTMENT_RESOLVE = 'INVESTMENT_RESOLVE';
export const INVESTMENT_REJECT = 'INVESTMENT_REJECT';
export const INVESTMENT_CANCEL = 'INVESTMENT_CANCEL';

export const INVESTMENTS_FETCH = 'INVESTMENTS_FETCH';
export const INVESTMENTS_RESOLVE = 'INVESTMENTS_RESOLVE';
export const INVESTMENTS_REJECT = 'INVESTMENTS_REJECT';
export const INVESTMENTS_CANCEL = 'INVESTMENTS_CANCEL';