export const WITHDRAWAL_FETCH = 'WITHDRAWAL_FETCH';
export const WITHDRAWAL_RESOLVE = 'WITHDRAWAL_RESOLVE';
export const WITHDRAWAL_REJECT = 'WITHDRAWAL_REJECT';
export const WITHDRAWAL_CANCEL = 'WITHDRAWAL_CANCEL';

export const WITHDRAWALS_FETCH = 'WITHDRAWALS_FETCH';
export const WITHDRAWALS_RESOLVE = 'WITHDRAWALS_RESOLVE';
export const WITHDRAWALS_REJECT = 'WITHDRAWALS_REJECT';
export const WITHDRAWALS_CANCEL = 'WITHDRAWALS_CANCEL';